### ISSUE TITLE
Docs look great!

### ISSUE THREAD

**Issue by adelevie** [USDA/RIDB#1]
Just wanted to thank you all for making this http://usda.github.io/RIDB/. I'll try to spend some more time to figure out how this could be made better, but it looks great so far.

**Comment by GitStu** [comment]
Thank you, Alan.  We just got this set up this week.  We’d love to hear more feedback for improvement from you on the GitHub site and on our new RIDB API as well.

Thx again!
Stu

[Forest Service Shield]

Stu Gregory
RIDB Program Manager, PMP

US Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 385-235-2971
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[http://wwwstatic.fs.usda.gov/images/email/usda-logo.png]<http://usda.gov/>[Twitter Logo]<https://twitter.com/forestservice>[Facebook Logo]<http://facebook.com/USDA>

Caring for the land and serving people

**Comment by danparker-nsite** [comment]
Agreed, thanks Alan! We appreciate your input once you've had a chance to take a look at everything.

Regards,
Dan Parker
