### ISSUE TITLE
Retrieve campsite availability data?

### ISSUE THREAD

**Issue by samjbobb** [USDA/RIDB#10]
Howdy! 

How does one retrieve availability data for a campsite?

For example, the [Bald Butte Lookout, OR campsite](http://www.recreation.gov/camping/Bald_Butte_Lookout/r/campsiteCalendar.do?page=calendar&search=site&contractCode=NRSO&parkId=75026) has Reserved/Available data on a per-day basis through the web interface on the Date Range Availability tab. The corresponding facility entity is: https://ridb.recreation.gov/api/v1/facilities/234186 and it's single campsite entity: https://ridb.recreation.gov/api/v1/facilities/234186/campsites/88103.

I haven't been able to find the availability data through the API. 

There does not seem to be any mention of this data in the API documentation. However the response to issue 9 (USDA/RIDB/issues/9) indicates that this data is available and updated nightly.

Any help?

Sorry if I've missed something obvious. I love this dataset and hope we can clear this up! Thanks!

**Comment by GitStu** [comment]
Hi,
The RIDB API does not give real-time availability at this time.  A separate database populated the RIDB weekly with availability data, but it is not in real-time.  We are looking into being able to provide that in the future, but we do not have a time estimate yet.

Thanks for your interest in the RIDB and Recreation.gov.

[Forest Service Shield]

Stu Gregory
RIDB Program Manager, PMP

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 385-235-2971
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[http://wwwstatic.fs.usda.gov/images/email/usda-logo.png]<http://usda.gov/>[Twitter Logo]<https://twitter.com/forestservice>[Facebook Logo]<http://facebook.com/USDA>

Caring for the land and serving people

**Comment by samjbobb** [comment]
Hi Stu, thanks for your response!

So how do we access the availability data that's added weekly? I can't seem to find an API endpoint with any data like that.

In lieu of that, can we call that second separate database?

**Comment by danparker-nsite** [comment]
Samjbobb,

Availability information is not available in the RIDB at this time. We've corrected the comments in issue #9 to reflect this. Our apologies for the confusion.

Regards,
Dan Parker

**Comment by samjbobb** [comment]
Thanks for the info. Looking forward to that update!

**Comment by GitStu** [comment]
Sorry, Sam.  I'm fairly new to the program and still sorting out details.  We currently do not have the ability to share availability data (whether real-time or delayed) although we are evaluating our options for doing that in the future.  Availability data is not being fed to the RIDB weekly.  Again, sorry for my mix-up.

**Comment by mnovinger** [comment]
Came here looking for the same thing, thanks for the detailed response to the question. Love the data as in, I was totally floored when I found it, thank you! Hoping you will be able to sort out the availability data at some point too!

**Comment by jeremyakers** [comment]
Any updates to this? This would be very useful.

**Comment by GitStu** [comment]
Hello – We still don’t have the ability to provide campsite availability data under our current/old contract.  We are now under a second/new contract that will replace the other and that will stand up a new Recreation.gov system in Oct 2018.  Sometime after go-live of the new site/system in Oct we will be looking into how we can provide campsite availability under the new contract.

[Forest Service Shield]

Stu Gregory
RIDB Data Manager

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/>[Forest Service Twitter]<https://twitter.com/forestservice>[USDA Facebook]<https://www.facebook.com/pages/US-Forest-Service/1431984283714112>

Caring for the land and serving people
