### ISSUE TITLE
Data download lacks connector data

### ISSUE THREAD

**Issue by ganley** [USDA/RIDB#12]
The full JSON and CSV data downloads appear to lack the connector data, that provides the links between different entities, such as between RecAreas and Facilities. See RecAreaActivity, FacilityActivity, RecAreaFacility, etc., defined in the data dictionary - none of this data seems to be in the full data download.

**Comment by danparker-nsite** [comment]
Ganley,

The connectors between the recreation areas and facilities to activities is in the EntityActivities file export. We will update the data dictionary and the ERD to reflect this change. We recently learned that we are missing connector information for events as well as connectors between facilities and recreation areas. Than you for your patience as we work to get these added in the short term.

We will leave this issue open until all connector/relationship issues are resolved.

Regards,
Dan Parker

**Comment by danparker-nsite** [comment]
Export files have been added to provide connector information for the following:
* orgentities - connects organizations to recreation areas and facilities
* reacareafacilities - connects parent recreation areas to child facilities

The Event export file has been modified to include entity ID and entity type. This connects events to recreation areas and facilities.

ERD and data dictionary updated in the API documentation to reflect the naming convention of "EntityActivities" vs. FacilityActivities/RecAreaActivities
