### ISSUE TITLE
/recareas with parameters appears broken.

### ISSUE THREAD

**Issue by exiquio** [USDA/RIDB#15]
https://ridb.recreation.gov/api/v1/recareas?latitude=39.7392&longitude=104.9903&radius=500&limit=10&apikey=NNNNNNNN

I was working on some code tonight trying to pull rec sites based on location. Unfortunately I kept receiving an empty result set. If you remove the optional parameters you will get results, but with them, one receives and empty results set.  Before I almost settled on it being my code, I tried another end point.

https://ridb.recreation.gov/api/v1/facilities?latitude=39.7392&longitude=104.9903&radius=500&limit=10&apikey=NNNNNNNN

With this endpoint, we receive the expected behavior, namely results driven by parameters.

**Comment by StageOne** [comment]
If you update your longitude value to a negative 104.9903, you'll get a few more recarea results.  
39.7392, -104.9903

https://ridb.recreation.gov/api/v1/recareas?latitude=39.7392&longitude=-104.9903&radius=500&limit=10&apikey=NNNNNNNN

Unfortunately, the results returned for facilities may be incorrect and need to be updated with correct latitude/longitude values.

**Comment by exiquio** [comment]
Thanks.

**Comment by danparker-nsite** [comment]
This ticket is complete. The parameter value needed adjusted.
