### ISSUE TITLE
Data woefully out of date

### ISSUE THREAD

**Issue by musicalsaw** [USDA/RIDB#16]
The latest event I could find was in October 2013.  (Using https://ridb.recreation.gov/api/v1/events/)
Surely there must have been at least one event in the last two and a half years!

**Comment by danparker-nsite** [comment]
The events data isn't used (much) by the agencies at this time. There are some records that are clearly test data that we'd like to clean out. What you are seeing accurately represents the events data, which as you indicated, is out of date. I'll discuss this with the RIDB team to see if it makes sense to document that the event data isn't currently in use.

**Comment by danparker-nsite** [comment]
We've cleaned up the events to remove the bad data. There are currently no active events in the RIDB.
