### ISSUE TITLE
Availability Data

### ISSUE THREAD

**Issue by smokEdbear** [USDA/RIDB#17]
up until recently I was able to pull campsite availability from Active (ie reserveAmerica).  without warning and without any explanation they removed this service.  this results in a huge loss of data for many websites because reserveAmerica now controls the vast majority of all national and state park campsites.

Would it be possible to have campsite availability data added to the RIDB database?

**Comment by GitStu** [comment]
Thank you for your inquiry.  The RIDB is not set up to accommodate reservation availability data.

[Forest Service Shield]

Stu Gregory
RIDB Program Manager, PMP

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 385-235-2971
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[http://wwwstatic.fs.usda.gov/images/email/usda-logo.png]<http://usda.gov/>[Twitter Logo]<https://twitter.com/forestservice>[Facebook Logo]<http://facebook.com/USDA>

Caring for the land and serving people
