### ISSUE TITLE
Field names are misspelled or misstated in the RIDB API Data Dictionary

### ISSUE THREAD

**Issue by nicaford** [USDA/RIDB#18]
Throughout the schema, we uncovered small discrepancies in the published Data Dictionary versus the JSON output being generated by the API.  Here is a list of these discrepancies:

1. In "Recreational Activity" the fields "ActivityName" and "ActivityLevel" are improperly prefixed with "Rec" in the data dictionary.
2. In "Campsite" the field "CampsiteAccessible" is misspelled as "CampsiteAccesible" in the data dictionary.
3. In "Campsite" the "LastUpdatedDate" field is misspelled as "LastUpdateDate" in the data dictionary.
4. In "FacilityAddress" the "FacilityAddressID" field is misstated as "AddressId" in the data dictionary.
5. In "PermitEntrance" the "PermitEntranceAccessible" field is misspelled as "PermitEntranceAccesible" in the data dictionary.
6. In "RecAreaAddress" the "RecAreaAddressID" field and the three "RecAreaStreetAddress" fields are missing the "RecArea" prefix in the data dictionary.

**Comment by danparker-nsite** [comment]
Thank you for the corrections. This is likely confusion in the the translation of database field names to API field names. We will work to correct the data dictionary in order to be consistent with the API terminology.

**Comment by danparker-nsite** [comment]
We've (finally) made the corrections to the data dictionary. Thanks again for bringing these to our attention. Closing this ticket
