### ISSUE TITLE
Default output is XML, but docs say default is JSON

### ISSUE THREAD

**Issue by mikelmaron** [USDA/RIDB#2]

**Comment by danparker-nsite** [comment]
Thank you for the correction! We've updated the documentation.

**Comment by danparker-nsite** [comment]
Mikel, we're having an internal discussion and I believe I've reverted my opinion that JSON is the default behavior. If you don't specify the type, the raw request says "Content-Type: application/json;charset=utf-8". Our code specifically sets the default to JSON as well. 

If I may, why were you reporting the default is XML?

**Comment by mikelmaron** [comment]
@danparker-nsite, I just checked again. Simply loaded https://ridb-dev.nsitellc.com/api/v1/recareas?apikey=XXXX and https://ridb-dev.nsitellc.com/api/v1/organizations?apikey=XXXX (substituting my key), and received an XML response.

That's strange that you are seeing json by default. Let me know if there's anything I can help with to debug.

IMHO, JSON default would be the way to go.

**Comment by mikelmaron** [comment]
@danparker-nsite, I just checked again. Simply loaded https://ridb-dev.nsitellc.com/api/v1/recareas?apikey=XXXX and https://ridb-dev.nsitellc.com/api/v1/organizations?apikey=XXXX (substituting my key), and received an XML response.

That's strange that you are seeing json by default. Let me know if there's anything I can help with to debug.

IMHO, JSON default would be the way to go.

**Comment by GitStu** [comment]
Thanks, Mikel.
We are working on getting the default changed to JSON, and agree that should be the default at this time.

[Forest Service Shield]

Stu Gregory
RIDB Program Manager, PMP

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 385-235-2971
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[http://wwwstatic.fs.usda.gov/images/email/usda-logo.png]<http://usda.gov/>[Twitter Logo]<https://twitter.com/forestservice>[Facebook Logo]<http://facebook.com/USDA>

Caring for the land and serving people

**Comment by danparker-nsite** [comment]
We've confirmed the application is setting  "application/json;charset=utf-8" as the default. Browsers may request the data as XML depending on how they evaluate the accept header if an extension isn't explicitly passed.

Thanks,
Dan
