### ISSUE TITLE
Returned query parameters are presented as incorrect type

### ISSUE THREAD

**Issue by nicaford** [USDA/RIDB#23]
When performing a RIDB API search, pages of results are returned in a wrapper.  Part of this wrapper contains the query parameters that were used in the search.  The "OFFSET" and "LIMIT" values provided back are formatted as floats when they should be integers.  For instance, instead of receiving a value of "50" for "LIMIT", a value of "50.0" is returned.

**Comment by danparker-nsite** [comment]
Understood on float vs integer. Agreed these should be integers. We will correct.

**Comment by danparker-nsite** [comment]
We've deployed the fix for the OFFSET and LIMIT parameters. They are now integers. Thanks for your patience!
