### ISSUE TITLE
are there limits on objects returned by queries?

### ISSUE THREAD

**Issue by thecaddy** [USDA/RIDB#26]
I'm performing queries on the various tables trying to pull all of them with respect to the Organization and Facitility but I noticed I'm only getting 50 objects returned at any time.  The documents don't indicate any limits on these requests.  I wrote a short script hitting all the org id's:

`/organizations/{OrgID}/recareas`

```
RecArea Count[0] American Battle Monuments Commission
RecArea Count[0] Bureau of Engraving and Printing
RecArea Count[50] Bureau of Land Management
RecArea Count[50] Bureau of Reclamation
RecArea Count[0] Department of Agriculture
RecArea Count[0] Department of Commerce
RecArea Count[0] Department of Defense
RecArea Count[0] Department of the Interior
RecArea Count[0] Department of the Treasury
RecArea Count[50] Department of Transportation
RecArea Count[0] Fairfax County
RecArea Count[0] Fairfax County Park Authority
RecArea Count[0] FEDERAL
RecArea Count[50] Fish and Wildlife Service
RecArea Count[0] Historic Hotels of America
RecArea Count[17] National Archives and Records Administration
RecArea Count[0] National Historic Landmark
RecArea Count[42] National Oceanic and Atmospheric Administration
RecArea Count[50] National Park Service
RecArea Count[0] National Register of Historic Places
RecArea Count[0] PRIVATE
RecArea Count[0] ReserveAmerica
RecArea Count[0] Smithsonian Institution
RecArea Count[5] Smithsonian Institution Affiliations Program
RecArea Count[0] STATE
RecArea Count[31] Tennessee Valley Authority
RecArea Count[0] US Air Force
RecArea Count[50] US Army Corps of Engineers
```

**Comment by danparker-nsite** [comment]
The default (and max) results on an API data request is 50. This is explained in more detail in the API documentation under the pagination section: http://usda.github.io/RIDB/#pagination

The pagination details are included with each response. Example:
```
<METADATA CF_TYPE="struct">
  <SEARCH_PARAMETERS CF_TYPE="struct">
  <QUERY></QUERY>
  <OFFSET>0</OFFSET>
  <LIMIT>50</LIMIT>
  </SEARCH_PARAMETERS>
  <RESULTS CF_TYPE="struct">
    <TOTAL_COUNT>20041</TOTAL_COUNT>
    <CURRENT_COUNT>50</CURRENT_COUNT>
  </RESULTS>
</METADATA>
```
If you prefer to download all the RIDB data in one download, you can learn more here: http://usda.github.io/RIDB/#get-all-rec-area-data

**Comment by thecaddy** [comment]
Thanks for the quick response.  I'm working on direct integration with ridb so using the api to update our records is of value.  I completely overlooked the pagination section.

**Comment by danparker-nsite** [comment]
I just realized who "thecaddy" is. Joel from Topophi! Great news to hear you are starting to work with the API. Please don't hesitate to reach out to us directly (ridbsupport@nsitellc.com) if you have more questions, though I'm sure the RIDB community would appreciate seeing the dialog here on GitHub. Looking forward to seeing the Topophi team again soon.

**Comment by thecaddy** [comment]
Absolutely we finally have a platform we are happy with and are focused on enriching our material and a lot of the ridb data fits like a glove.  If we have any additional questions I'll post it here.  Also feel free to reach out if there is anything we can help with as well.  You can reach me at  joel@topophi.com.

**Comment by GitStu** [comment]
Joel – Great to hear that the RIDB data is complementing your application nicely.  Thanks for the feedback!

Stu
