### ISSUE TITLE
Releases for RIDB

### ISSUE THREAD

**Issue by thecaddy** [USDA/RIDB#27]
I notice the api endpoint has /v1.  Are there incremental ongoing changes with the api in terms of data or is this set in stone?

**Comment by danparker-nsite** [comment]
Joel,

The structure in V1 will remain constant but we will add new versions in the future with different endpoints/data elements. Does this answer your question?

**Comment by thecaddy** [comment]
Is there a changelog or proposals for future updates to ridb?

**Comment by danparker-nsite** [comment]
We will put a change log out here on GitHub once we start making modifications to the API. No proposals yet for future updates, but you are welcome to use this issue tracker to add recommendations or reach out to us directly at ridbsupport@nsitellc.com.

**Comment by thecaddy** [comment]
Great thanks, I'll open up some issues.
