### ISSUE TITLE
Fire Levels for Recreation Areas

### ISSUE THREAD

**Issue by thecaddy** [USDA/RIDB#28]
It would be great to see the fire levels of respective areas.  A bonus to this would be historical fire level data.

**Comment by GitStu** [comment]
Thanks, Joel, for your comments.  I was doing some email catch-up after a trip I was on a couple of weeks.  Sorry for the late reply.  I have collected all your comments you sent in, and I appreciate them – especially the one below.  I am going to begin talking this up and looking into possibilities and options for presenting and linking up with fire data and possibly interactive mapping capability.  We’re currently somewhat restricted by what we can implement on Rec.gov now, but our future contract’s scope is written to more widely enable geospatial data and functionality.  We are also beginning work this fall on preparing the RIDB to accept and store GIS/geospatial data for use in the future contract (2016-17 est. begin) and on Rec.gov.  We intend to engage the public and ask what they would like to see and do on Rec.gov so we can obtain data and develop functionality that meets those desires.  I’m going to consider your suggestion below as our first user feedback item.  Thanks again!  And thanks for using the RIDB and sending other helpful suggestions too.

Have a great long weekend!

[Forest Service Shield]

Stu Gregory
RIDB Program Manager, PMP

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[http://wwwstatic.fs.usda.gov/images/email/usda-logo.png]<http://usda.gov/>[Twitter Logo]<https://twitter.com/forestservice>[Facebook Logo]<http://facebook.com/USDA>

Caring for the land and serving people

**Comment by danparker-nsite** [comment]
Joel,

We recently learned of a public fire data resource named [Inciweb](http://inciweb.nwcg.gov/), and they have a KML [feed](http://inciweb.nwcg.gov/feeds/maps/kml/)! We are considering pulling this data into the RIDB in the future, but I wanted to get the link to you in the meantime.
