### ISSUE TITLE
GeoJSON Output Format

### ISSUE THREAD

**Issue by mikelmaron** [USDA/RIDB#3]
Most responses seem to be a flat set of properties, with two being lat/lon. This could translate into GeoJSON very easily. Benefit would use of open standard and quick integration into lots of web mapping and GIS tools.

**Comment by danparker-nsite** [comment]
Mikel,

Thanks for the suggestion about providing the latitudes and longitude data as GeoJSON. We'll evaluate the level of effort on this to see if we can accomplish before go live.

**Comment by danparker-nsite** [comment]
GeoJSON is now available on all resources containing latitude and longitude data. Thanks again for making this recommendation.
