### ISSUE TITLE
API Queries

### ISSUE THREAD

**Issue by rhsu0268** [USDA/RIDB#31]
Hi, 

I am having some trouble with making some requests to the API:

Suppose I wanted to do the query for organization: 

https://ridb.recreation.gov/api/v1/organizations/

That query is giving me 404 Not Found even after I ented my api key for api. 

Are there parameters that I need?

**Comment by rhsu0268** [comment]
Sorry, 

I had the wrong format for key. 

Got it working!

**Comment by danparker-nsite** [comment]
Great news. Thanks for the update
