### ISSUE TITLE
API

### ISSUE THREAD

**Issue by rhsu0268** [USDA/RIDB#32]
Hi, 

I have some questions in regards to the RIDB API that might be more geared towards the organizations who made all of this possible:

1. How often are the events being updated? I tried a few sample queries but couldn't see any. Also, can you recommend good sources for events that are in the form of either a.) API or b.) Aggregated site for scraping purposes

2. Are there sample queries for facilities? I tried looking at a few in my browser, but wasn't seeing anything with some queries?

Thanks,

**Comment by GitStu** [comment]
Hi – we’ll get back to you shortly.  Thanks for your patience.

[Forest Service Shield]

Stu Gregory
RIDB Program Manager, PMP

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[http://wwwstatic.fs.usda.gov/images/email/usda-logo.png]<http://usda.gov/>[Twitter Logo]<https://twitter.com/forestservice>[Facebook Logo]<http://facebook.com/USDA>

Caring for the land and serving people

**Comment by rhsu0268** [comment]
Hi Stu, 

Just a friendly note. Still waiting on a response to my inquiries. 

Please let me know if the RIDB team has anything on those. 
Thanks,
Richard

**Comment by danparker-nsite** [comment]
Richard,

Our apologies for the delay. Stu is on travel this week, but he's researching the event question to provide you with some useful information. In the short term, you are absolutely correct about not seeing any events in the RIDB. There are currently no active events. 

For question #2 about facilities, the API documentation for facilities is here:http://usda.github.io/RIDB/#facilities. 

You can see all facilities here: https://ridb.recreation.gov/api/v1/facilities/?apikey=myAPIKey. 

You can search for a facility like so: https://ridb.recreation.gov/api/v1/facilities/?query=yosemite%20south&apikey=myAPIKey 

Was there a query where you expected to see results and didn't?

**Comment by GitStu** [comment]
Hi Richard,
Sorry for my delay.  I initiated some coordination on this earlier in the week, but I need to resume and finish with a response when I’m free from travel status and meetings all this week.  I’ll be back in touch  with a full response later today or Monday.

[Forest Service Shield]

Stu Gregory
RIDB Program Manager, PMP

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[http://wwwstatic.fs.usda.gov/images/email/usda-logo.png]<http://usda.gov/>[Twitter Logo]<https://twitter.com/forestservice>[Facebook Logo]<http://facebook.com/USDA>

Caring for the land and serving people

**Comment by rhsu0268** [comment]
Hi Stu, 

Thanks, I will wait for your response.

**Comment by GitStu** [comment]
Hello,

1.       Events aren’t currently being used in the RIDB. There are no active events in the system at this time. Agency websites would be a good source for events, but I can’t speak to the accuracy of screen scraping of the agency sites, and I don’t know what agency sites may be ‘advertising’ events at this time. I’m also not aware of any APIs for agency events.  Events may be added/included in the RIDB in the future, but those would be at the discretion and timing of the specific agency.

2.       Facility queries:

a.       Overall Facility documentation: http://usda.github.io/RIDB/#facilities

b.       Get all facilities: https://ridb.recreation.gov/api/v1/facilities/?apikey=myAPIKey

c.       Get facilities like “Yosemite South”: https://ridb.recreation.gov/api/v1/facilities/?query=yosemite%20south&apikey=myAPIKey


Stu

**Comment by rhsu0268** [comment]
Hi Stu,

Thank you so much for the responses. My team was hoping to get the events for some of these recAreas but we might have resort to screen scraping if we can't find any APIs that allow us to query for events. 

Thanks for your help. 

Richard
