### ISSUE TITLE
RIDB campsite data includes only reservable sites (?)

### ISSUE THREAD

**Issue by gizm00** [USDA/RIDB#33]
Hi, and thanks for this fantastic resource! I noticed that first come, first serve campsites are missing from the campsites endpoint, at least in these cases I have come across:

I noticed that the campsites returned from RIDB specifically for facilityid 251434 - LOST LAKE RESORT AND CAMPGROUND - includes only the 84 reservable sites. There are some 120+ sites at the campground, with the rest on a first come, first serve basis. I also checked a few other facilityids for facilities that are entirely first come, first serve. There are 8 and 6 sites at Bonney Crossing (facilityid 235784) and Bonney Meadow (facilityid 235785) respectively, but the campground api returns 0 campsites for both facilities.

Im querying the campsite info from this API endpoint:

https://ridb.recreation.gov/api/v1/facilities/{facilityid}/campsites

Does RIDB only have data on reservable campsites as a rule? 

Thanks!

**Comment by danparker-nsite** [comment]
Thanks for your interest in the RIDB API's campsite level data. You are absolutely correct, the API only has site level data for reservable campsites. First come, first serve sites are not available at this time. We'll update the API documentation to clarify only reservable campsites are in the RIDB at this time.

**Comment by danparker-nsite** [comment]
API documentation updated to state "The RIDB campsite resources only contain reservable campsites. First come, first serve campsites are not available at this time."

http://usda.github.io/RIDB/#campsites
