### ISSUE TITLE
Increase max facilities returned?

### ISSUE THREAD

**Issue by brightrain** [USDA/RIDB#34]
Any consideration and\or other requests to increase the maximum number of facilities returned in a request? I'm building an interactive web map that shows recreation facilities in the current map extent and the 50 max is difficult to overcome at lower zoom levels. For example, if I am at zoom level 10 almost anywhere in Colorado the max is exceeded.

Maybe make 50 the default with the option to set higher like 100 or 200 with a max of 200?

The prototype app is here if you are interested:
http://www.dev.brightrain.com/recreationer/

And the repo is here:
https://github.com/brightrain/ridb-recreationer

**Comment by danparker-nsite** [comment]
David,

Thanks for your interest in the RIDB API. Great job on your prototype!

We haven't had any other requests to increase the max record count yet on the API responses. We settled in on 50 to keep the data packets in the responses light. If you add the "full" parameter to the request, it can really return quite a bit of data. 

Have you seen the pagination information we return along with the response body? You can use the pagination information to iterate through the result set to get everything in your proximity and then display all the results to the screen. We have some documentation on pagination [here](http://usda.github.io/RIDB/#pagination).

**Comment by brightrain** [comment]
Ah, no hadn't seen the pagination info. Sounds like that will get me where I need to be. Thanks for the info and I'll go ahead and close.
