### ISSUE TITLE
Latest Chrome Browser cannot access ridb.recreation.gov website & ridb API errors ERR_SSL_FALLBACK_BEYOND_MINIMUM_VERSION 

### ISSUE THREAD

**Issue by ferrellcharles** [USDA/RIDB#35]
I upgraded to the latest Chrome browser version 50 this morning, and now can no longer access https://ridb.recreation.gov  Chrome reports that "The site can't provide a secure connection." with error ERR_SSL_FALLBACK_BEYOND_MINIMUM_VERSION.  

I'm thinking this could be related to Google slowly deprecating older versions of SSL.  Here is a link to some information I found about it:  http://www.rbrussell.com/2015/09/15/google-chrome-error-ssl-server-probably-obsolete-err_ssl_fallback_beyond_minimum_version/

I was able to get to the ridb.recreation.gov website this morning by opening via FireFox in order find the info to this support forum.  Then, I tested on an old computer that still has Chrome version 49, and it was still able to access ridb.recreation.gov.  

I know this is going to be a pain for a lot of folks needing to upgrade servers, but I guess it's better save than sorry as far as security.

Also of interest to some may be that Chrome requires https if you use the geolocation API in your web app.  I found this article from January 2016:  https://mobiforge.com/news-comment/no-https-then-bye-bye-geolocation-in-chrome-50 discussing what was going to happen with version 50.  Luckily, I had upgraded my web app to https in February, so I've also tested (by default) that the geolocation does continue to work in my web app today after having upgraded to version 50.  So if anyone is getting errors with geolocation in their web app in Chrome, you may be forced to start using https if you aren't already.

**Comment by danparker-nsite** [comment]
Charles,
Thanks for opening this issue. The SSL cert is SHA-2 but the fallback was "falling back" too far. We've corrected the issue and we can now view the site on HTTPS with Chrome Version 50.0.2661.75 m. Would you mind trying again?

Thanks again,
Dan

**Comment by ferrellcharles** [comment]
Thanks for the quick response, Dan.  I noticed earlier this afternoon that
the issue had been corrected and I am indeed able to access the API as well
as the website on Chrome 50 now :-)  Everything is working great!

Glad you are still working with RIDB team.  You are always quick to address
issues and get them resolved and you are greatly appreciated.  I hope they
have given you a raise since we last spoke!

Thanks again and have a good night,
Charles

**Comment by danparker-nsite** [comment]
Thanks for the kind words, Charles. Glad to see you are still using the RIDB data!

**Comment by GitStu** [comment]
Thanks for your feedback, Charles.  I agree with your fine assessment of Dan!

[Forest Service Shield]

Stu Gregory
R1S Data Manager, PMP

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/>[Forest Service Twitter]<https://twitter.com/forestservice>[USDA Facebook]<https://www.facebook.com/pages/US-Forest-Service/1431984283714112>

Caring for the land and serving people
