### ISSUE TITLE
Looking for tickets available for a given tour exposed in API

### ISSUE THREAD

**Issue by bluepete** [USDA/RIDB#38]
We are working on a project with NPS and have been tasked with showing whether or not tickets are available (and possibly how many are left) for a given time slot for the [Independence Hall Tour in Independence National Historical Park, Philedelphia, PA](http://www.recreation.gov/tourDetails.do?contractCode=NRSO&tourId=212619) on a digital display.

We are interested in accessing how many tickets are available for the tour and each time slot via the API. This can be done on the website so we know the data exists, but there doesn't seem to be a call in the API outlining how access this data.

![screen shot 2016-07-27 at 1 15 06 pm](https://cloud.githubusercontent.com/assets/6749762/17184946/d07e0744-53fc-11e6-8ffd-8251ed1d8362.png)

Any assistance you can provide would be greatly appreciated. Thank you!

**Comment by GitStu** [comment]
We don't currently have the ability to show real-time ticket availability through the RIDB API, but we will be investigating the development of this functionality when we begin our new program support contract beginning this fall.  An API "availability" development schedule will be established after the contract begins in Sep or Oct.

**Comment by GitStu** [comment]
I'll see if our current contract's scope can accommodate this, but I do not think we currently can provide this capability.  I'll follow-up here when I confirm either way.

**Comment by GitStu** [comment]
We will have to wait for availability data to be developed under the next/new Recreation One Stop program contract beginning in Sep or Oct.

**Comment by danparker-nsite** [comment]
Thanks for the update, Stu. Closing this ticket.
