### ISSUE TITLE
Data Not In Sync With Reservation System

### ISSUE THREAD

**Issue by tjmike** [USDA/RIDB#39]
Using the full data from :

https://ridb.recreation.gov/?action=datadownload

I get the following row for ASSATEAGUE ISLAND NATIONAL SEASHORE, MD Site B34 from the Campsites_API_v1.csv table:

CAMPSITEACCESSIBLE,CAMPSITEID,CAMPSITENAME,CAMPSITETYPE,CREATEDDATE,FACILITYID,LASTUPDATEDDATE,LOOP,TYPEOFUSE
"No","6485","B34","STANDARD NONELECTRIC","2014-05-02 17:20:13","232507","2016-03-03 05:00:45","Bayside Loop B","Overnight"

Given the CAMPSITEID of  6485. I try to look it up in the  PermittedEquipment_API_v1.csv table to find the length for that site. However, that table seems to be missing a bunch of rows including this one. If I grab all the CAMPSITEIDs and sort them I find a hole from 6455-6486. 

6453
6454
6487
6488
6489

I'm assuming that the data I fetch from the data download should be the same as that found on when searching campsites here:

 http://www.recreation.gov/campsiteSearch.do

For the  ASSATEAGUE ISLAND NATIONAL SEASHORE site there are lots of PermittedEquipment equipment entries missing or wrong. For example I cannot find one site at 40' or over when looking data up in the database, but I was able to find 47 on the search above.

It seems like the datadownload tables are not in sync with the web site data. Can this be fixed or is there some way to get data that is in sync?

**Comment by danparker-sts** [comment]
tjmike,

Thanks for reporting the issue. We're digging into the permitted equipment data to find out why some of the campsites don't have and associated permitted equipment entry or the entry is wrong. 

We'll be in touch as we learn more.

Thanks for your patience,
Dan

**Comment by tjmike** [comment]
Just checking in on this to see how it's going. Also, offering assistance
if there is anything I can do to help out.

**Comment by danparker-sts** [comment]
tjmike,

Unfortunate;y we haven't found any patterns in the missing permitted equipment data. There appear to be 16,044 campsites that don’t have a corresponding permitted equipment record. Some of these don’t have any permitted equipment such as ACKER ROCK LOOKOUT, but many others should have one to indicate the max equipment length. Unfortunately I don’t have a way to tell which records should or shouldn’t have a permitted equipment record, so we've reached out to the contractor that manages the reservable data to assist in the investigation and correction. 

Thanks again for your patience as we work to correct the issue.

Regards,
Dan

**Comment by danparker-sts** [comment]
tjmike,

I'm pleased to report the permitted equipment issue has been resolved. All permitted equipment in recreation.gov should now be consistently be shared in the RIDB. Thanks again for your patience as we worked to resolve this issue.
