### ISSUE TITLE
PermittedEquipment_API_v1 missing in in JSON full download

### ISSUE THREAD

**Issue by tjmike** [USDA/RIDB#40]
Here's a list of the files in the full csv and json downloads:

Activities_API_v1.csv
Attributes_API_v1.csv
Campsites_API_v1.csv
EntityActivities_API_v1.csv
Events_API_v1.csv
Facilities_API_v1.csv
FacilityAddresses_API_v1.csv
Links_API_v1.csv
Media_API_v1.csv
MemberTours_API_v1.csv
OrgEntities_API_v1.csv
Organizations_API_v1.csv
PermitEntranceZones_API_v1.csv
PermitEntrances_API_v1.csv
PermittedEquipment_API_v1.csv
RecAreaAddresses_API_v1.csv
RecAreaFacilities_API_v1.csv
RecAreas_API_v1.csv
Tours_API_v1.csv

Activities_API_v1.json
Attributes_API_v1.json
Campsites_API_v1.json
EntityActivities_API_v1.json
Events_API_v1.json
Facilities_API_v1.json
FacilityAddresses_API_v1.json
Links_API_v1.json
Media_API_v1.json
MemberTours_API_v1.json
OrgEntities_API_v1.json
Organizations_API_v1.json
PermitEntranceZones_API_v1.json
PermitEntrances_API_v1.json
RecAreaAddresses_API_v1.json
RecAreaFacilities_API_v1.json
RecAreas_API_v1.json
Tours_API_v1.json

PermittedEquipment seems to be missing in the json version.

**Comment by danparker-sts** [comment]
tjmike,

Thanks for reporting the missing JSON file. We've added it to the RIDB data JSON package, and it will be included in the nightly updates moving forward.

Thanks again,
Dan

**Comment by GitStu** [comment]
Dan – Sorry I didn’t get back to you earlier on this.  Also got your VM this morning.  Thanks for deploying.

Stu
