### ISSUE TITLE
Coordinate Mapping for Campsites & Loops

### ISSUE THREAD

**Issue by jpolete** [USDA/RIDB#41]
First of all thanks for this great resource. I'm just starting to dig into it. 

I don't see that I can get geolocation coordinates or map data for individual loops/campsites. How could I go about mapping individual campsites on a loop, similar to how recreation.gov listings show them? Is that possible through the API?

Thanks.

**Comment by GitStu** [comment]
You are correct that we do not have coordinate data for individual campground loops and sites.  We only have a coordinate for an entire campground, and unfortunately we do not get all those coordinates from the agencies who send us their recreation data.  The amount and quality of coordinate data has improved over the last couple of years, but there are still a bunch or records still missing the spatial data.  The campground maps on Rec.gov are not spatially enabled. Those maps are currently created as close approximations to give an idea of layout.  We are looking into how we can infuse our records to the site level with spatial and other data and will be making development enhancements to Recreation.gov when we enter our new program support contract some time next calendar year.  Thank you for your interest in the RIDB/Recreation.gov data.

**Comment by jpolete** [comment]
Thanks @GitStu. So I'm correct in saying that that campsite/loop map data is not publicly available, right?

**Comment by GitStu** [comment]
Not exactly correct...  It's not that the data isn't publicly available.  We aren't withholding that data.  It's that it doesn't exist for loops and individual campsites.  We have coordinates (spatial or map data) for many campgrounds (a grouping of loops and sites), but not for the individual components (the loops and sites).  The campground maps you see on the current Rec.gov have no real spatial qualities.  They are just pictures depicting approximate layouts.

**Comment by jpolete** [comment]
Gotcha. Sorry, I worded my question poorly. I meant to ask whether those loop maps (even though they're approximations) were available as some sort of assets through the API (svg, kml, etc.), in the same way that an image might be a related asset to a facility.

**Comment by GitStu** [comment]
Correct, those 'maps' are not available through the API.
