### ISSUE TITLE
0 out of 0 records found when 1 record displayed

### ISSUE THREAD

**Issue by paulinadao** [USDA/RIDB#44]
1. Navigate to https://ridb.recreation.gov/index.cfm?action=advsearch
2. Search for "PV Pit"

Expected: 1 out of 1 results displayed.
Actual: 0 out of 0

**Comment by danparker-sts** [comment]
"PV Pit Campground" appears as a Rec Area for BLM when I search for "PV Pit". Do you have any other search filters applied by any chance? I tested in Firefox and Internet Explorer.

**Comment by paulinadao** [comment]
@danparker-sts My apologies for unclear expected/actual. The search result itself is displayed but the text below shows 0 out of 0.

**Comment by danparker-sts** [comment]
Ah, I understand. Good catch! Labeling this issue as a bug. Thank you!

**Comment by danparker-sts** [comment]
We've corrected the 0/0 results issue. You may new to refresh your JS/CSS files to see the change. Thanks again for reporting the issue!
