### ISSUE TITLE
No data for GET to Trails

### ISSUE THREAD

**Issue by paulinadao** [USDA/RIDB#45]
1.  GET https://ridb.recreation.gov/api/v1/api/v1/trails/USFS/

Expected: Data is returned
Actual: HTML for RIDB is returned

**Comment by danparker-sts** [comment]
The trails data is currently unavailable. We are returning "The service is unavailable" when these endpoints are accessed.  We expect to have these endpoints operational again by Friday, 13 January.

**Comment by danparker-sts** [comment]
The trails endpoints have been enabled again and are performing as expected. Thank you for your patience!
