### ISSUE TITLE
Quick question!

### ISSUE THREAD

**Issue by gregruth** [USDA/RIDB#46]
I have been looking over the API and see a lot of useful methods but I was wondering if there were any for scheduling a campsite?

**Comment by GitStu** [comment]
The ability to schedule a campsite in the API is currently not available.  We may look into that option in the future, but nothing definitive yet.  Thanks for your interest in our data and the RIDB API.

**Comment by gregruth** [comment]
Could you provide any insight into how other services manage this?

**Comment by GitStu** [comment]
Currently I cannot, but not positive I completely understand the question.  Are "other services" other companies/entities that provide reservation services similar to Rec.gov?

**Comment by gregruth** [comment]
Yes, just like Rec.gov

**Comment by GitStu** [comment]
I'm not aware of other government services that enable scheduling of recreation inventory via an API.  There are probably private companies that offer this for other recreation opportunities that are not federally managed, but I'm not aware of them - Hip Camp might have some inventory that they offer reservations via API, but not sure.  We know there are members of the public who are interested in this ability, and we will be looking into this possibility as we begin development of the new Recreation.gov platform in the coming several months.

**Comment by gregruth** [comment]
Oh that's great! Is there a rec.gov blog I can follow?

**Comment by GitStu** [comment]
there is not.  However we might consider one in the context of the new development I mentioned, but we haven't begun that process yet - but close on the horizon!

**Comment by danparker-sts** [comment]
Closing this issue unless there's further discussion. Thanks for the collaboration!

**Comment by gregruth** [comment]
Hey I just wanted to check in and see if there were any updates :)

**Comment by GitStu** [comment]
The new Recreation.gov platform will go live in early October.  After that time we will be looking into the possibility of offering an API that shows availability of our inventory.  We do not have a schedule yet for that API development as we are in the middle of development of the new Rec.gov platform.

[Forest Service Shield]

Stu Gregory
RIDB Data Manager

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/>[Forest Service Twitter]<https://twitter.com/forestservice>[USDA Facebook]<https://www.facebook.com/pages/US-Forest-Service/1431984283714112>

Caring for the land and serving people

**Comment by gregruth** [comment]
Awesome! I'll check back in the fall then. I'm excited to start working with this data!
