### ISSUE TITLE
AuTrain Lake Campground Possibe Data issue

### ISSUE THREAD

**Issue by tjmike** [USDA/RIDB#47]
The web site seems to have equipment length info for AuTrain Lake. For example:

Site 1 shows an equipment length of 60 feet:

https://www.recreation.gov/camping/Autrain_Lake_Campground/r/campsiteDetails.do?contractCode=NRSO&siteId=273117&parkId=72064

Max Vehicle Length: 60

If I've done this right then the campsiteID is 78143. When searching the CSV files for info for this site I find the following information:

Attributes_API_v1.csv:"124022472","Checkin Time","3:00 PM","78143","Campsite"
Attributes_API_v1.csv:"124022473","Checkout Time","2:00 PM","78143","Campsite"
Attributes_API_v1.csv:"124022474","Driveway Entry","Back-In","78143","Campsite"
Attributes_API_v1.csv:"124022475","Driveway Surface","Gravel","78143","Campsite"
Attributes_API_v1.csv:"124022476","Grills/Fire Ring","Y","78143","Campsite"
Attributes_API_v1.csv:"124022477","Max Num of People","8","78143","Campsite"
Attributes_API_v1.csv:"124022478","Max Num of Vehicles","2","78143","Campsite"
Attributes_API_v1.csv:"124022479","Min Num of People","1","78143","Campsite"
Attributes_API_v1.csv:"124022480","Min Num of Vehicles","1","78143","Campsite"
Attributes_API_v1.csv:"124022481","Pets Allowed","Domestic","78143","Campsite"
Attributes_API_v1.csv:"124022482","Picnic Table","Y","78143","Campsite"
Attributes_API_v1.csv:"124022483","Shade","Partial","78143","Campsite"
Attributes_API_v1.csv:"124022484","Site Reserve Type","Site-Specific","78143","Campsite"
Attributes_API_v1.csv:"124022485","Campfire Allowed","Y","78143","Campsite"
Campsites_API_v1.csv:"No","78143","001","STANDARD NONELECTRIC","2014-05-02 18:19:21","233172","2017-05-04 05:15:19","AuTrain Lake Campground","Overnight"

I don't see the 60' information for this site in any of the tables. Is it missing or am I searching incorrectly?

**Comment by danparker-sts** [comment]
tjmike,

Please accept my sincerest apologies. We've been working with the recreation.gov data team on the permitted equipment issue and they were confident the last of the data inconsistencies had been resolved. We've brought this facility to their attention and will reply once resolved.

If there were permitted equipment data for campsite ID 78143, you would've found it in the permittedEquipment_API_v1.csv file

Do you have any insight regarding how you've found these data inconsistencies? There are about 12,000 campsites we've believed had no permitted equipment data in the recreation.gov system, but you seem to have found inconsistencies relatively easily. Any pointers to assist in debugging would be most appreciated. We'd very much like to fix any and all inconsistencies once and for all.

Thanks again for your patience,
Dan

**Comment by tjmike** [comment]
AuTrain was just dumb luck it was one of my test cases. It seems like:

BAY FURNACE CAMPGROUND, MI and AUK VILLAGE CAMPGROUND, AK may also be missing.

I've attached a .csv file that may be helpful. It shows campgrounds with missing (Column E, #Missing) length data. It would be possible to sample these on the web site to see if they are missing there as well. The files is attached as a .txt file because the .csv extension was not allowed. I hope this helps. 

If you provide some way to generate a site specific url. For example:

https://www.recreation.gov/camping/Autrain_Lake_Campground/r/campsiteDetails.do?contractCode=NRSO&siteId=273117&parkId=72064


then it would be possible to build a pretty complete list. Is there enough data provide to build the above string?




[candidates.txt](https://github.com/USDA/RIDB/files/994594/candidates.txt)

**Comment by danparker-sts** [comment]
tjmike,

Thanks again for the follow up. We're in touch with the contractor on the recreation.gov system and they are looking into the missing length information. I'll report back when I have something.

**Comment by danparker-sts** [comment]
tjmike,

The recreation.gov contractor deployed a change to include "max vehicle length" in the attribute data. I'm pleased to report that I'm seeing this data in the AuTrain, Bay Furnace, and Auk Village campground data.

Thanks again for your patience as they worked to resolve this issue.

Regards,
Dan

**Comment by tjmike** [comment]
Thank you for continuing to work on this. I did a little test and do see
about 7,200 new max length values via attributes.

- Mike

**Comment by danparker-sts** [comment]
Outstanding news, Mike. Thanks again for your patience and collaboration to get this additional attribute data flowing into the RIDB.
