### ISSUE TITLE
latitude and longitude parameter not working 

### ISSUE THREAD

**Issue by kristinakarrass** [USDA/RIDB#48]
Hi,

I am trying to get facilities by latitude/longitude and in a specific radius. My query with latitude and longitude returns an empty array, when I use lat and long, it returns campgrounds in Wyoming, no matter which coordinates I enter. Here is my URL for the query. Could you let me know if I'm doing something wrong? I have tried several different ways. The only way it has worked for me was by searching with the state parameter, but then I get way too many results. 
https://ridb.recreation.gov/api/v1/facilities/?query=camping&lat=40.7128&long=74.0059&radius=5&apikey=myapikey

Thank you.

**Comment by slouisin** [comment]
Thank you for contacting us, I see a couple issues with the query you are trying to use.

To use lat/long in the API it requires the full words "latitude" and "longitude."  The sample coordinates you provided looks like you were trying to search around New York City, but you need a negative longitude value (-74.0059).

sample url
https://ridb.recreation.gov/api/v1/facilities/?query=camping&latitude=40.7128&longitude=-74.0059&radius=50&apikey=[key]

I increased the radius to 50 miles to expand the search and return 4 facilities.

Thank you,
RIDB Support

**Comment by kristinakarrass** [comment]
Thank you for your reply. I have tried it with latitude and longitude before. I used the coordinates of Yosemite with a 100 mile radius and don't get any results back. Neither for some other places I've tried, where I know plenty of campgrounds should pop up. 

https://ridb.recreation.gov/api/v1/facilities/?query=camping&latitude=37.8651&longitude=119.5383&radius=100&apikey=[key]

I don't get any results back with this query, but I would like to get all campground within a specific radius per search. I'd really appreciate if you could give me some feedback.
Thanks.

**Comment by slouisin** [comment]
You just need the correct longitude, -119.5383.  The US is in the western hemisphere and all longitude values are negative.   Here is an interactive world map that may help with Latitude, Longitude:  http://www.latlong.net

https://ridb.recreation.gov/api/v1/facilities/?query=camping&latitude=37.8651&longitude=-119.5383&radius=100&apikey=[key]

Also, if you want to get all facilities that list camping as an activity, you can add a search parameter:

https://ridb.recreation.gov/api/v1/facilities/?activity=9&latitude=37.8651&longitude=-119.5383&radius=100&apikey=[key]

activity=9 is for camping.

Here is a link to all the available activities.  And remember to use the ID or number for the activity
https://ridb.recreation.gov/api/v1/activities/?apikey=[key]

Thank you,
RIDB Support

**Comment by kristinakarrass** [comment]
Hi again,

I am trying to get trails in a 50 mile radius from a specific point. I have tried several national parks like Yosemite and Yellowstone. In Yellowstone I get trails back that are located in the Grand Teton Park and in Yosemite trails that are about 100 miles off to the north east. 
https://ridb.recreation.gov/api/v1/trails/USFS/?latitude=" + lat + "&longitude=" + lng + "&radius=50&apikey=myapikey"

Latitude and Longitude working fine now and the campground calls returns results that are close to the point I enter, but the trails won't show up. Do you have any trails in Yosemite Valley for example in your database?

**Comment by slouisin** [comment]
Your API queries are correct, we do not have any US Forest Service trails in or near the two National Parks you listed.   And currently we don't have any of the National Park Service trails data available in the RIDB.

If look at the interactive map on the link below, you can see that the USFS trails all are outside the National Parks.
https://www.fs.fed.us/ivm/index.html

Thank you,
RIDB Support
