### ISSUE TITLE
Invalid longitude for Facility 261838

### ISSUE THREAD

**Issue by reidab** [USDA/RIDB#49]
The entry for Ute Trail Trailhead-Dotsero (ID: 261838) lists a longitude of `-1107.06519` when it should be closer to `-107`. I'm guessing the extra `1` is a typo.

**Comment by GitStu** [comment]
Reid – Thanks for bringing this to our attention.  I have passed this along to BLM folks who can look into it and fix within their agency.  Once fixed there, the system we have in place will then update the record on Rec.gov.  Might take a few days but not too long.  Feel free to ask for updates if you don’t see this fixed reasonably soon.

[Forest Service Shield]

Stu Gregory
RIDB Data Manager

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/>[Forest Service Twitter]<https://twitter.com/forestservice>[USDA Facebook]<https://www.facebook.com/pages/US-Forest-Service/1431984283714112>

Caring for the land and serving people

**Comment by reidab** [comment]
It looks like this has been corrected — thanks!
