### ISSUE TITLE
Kill the master branch 

### ISSUE THREAD

**Issue by gbinal** [USDA/RIDB#5]
After moving the readme over to gh-pages - https://github.com/USDA/RIDB/pull/4 - a few small things will tidy up the repo:  
* go into settings and change the default branch to gh-pages.  
* unpublish the master branch (holler if you need a hand doing that.  I just use the github desktop client and it takes 3 seconds).

**Comment by danparker-nsite** [comment]
Thanks for the recommendation. We appreciate the guidance. This item is complete.
