### ISSUE TITLE
Invalid facility email addresses

### ISSUE THREAD

**Issue by reidab** [USDA/RIDB#50]
Several facilities are listed with invalid email addresses:

ID | Name | Current Email Value | Presumed Correct Value
---|-------|---------------------|-----
261758 | Witch Pool | `para_interpretation` | `para_interpretation@nps.gov`
262587 | (blank? could also be an issue) | `BLM_CA_Web_UK` | `BLM_CA_Web_UK@blm.gov`
262624 | Boar's Tusk | `rock_springs_wymail@bl,.gov` | `rock_springs_wymail@blm.gov`
262661 | Simpsons Hollow | `rock_springs_wymail@blm` | `rock_springs_wymail@blm.gov`
262699 | Salmon Lake Campground | `907-267-1246` | `blm_ak_afo_general_delivery@blm.gov` (phone and email fields are swapped)
268206 | Route 66 (Piute Crossing) | `www.blm.gov/ca/needles` | Unknown
271941 | Wolford Red Desert Overlook | `970-724-3000` | Unknown

**Comment by GitStu** [comment]
As we prepare to switch to the new Recreation.gov that we are currently developing, we will be asking all our participating agencies to validate their data, including the ones below.

[Forest Service Shield]

Stu Gregory
RIDB Data Manager

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/>[Forest Service Twitter]<https://twitter.com/forestservice>[USDA Facebook]<https://www.facebook.com/pages/US-Forest-Service/1431984283714112>

Caring for the land and serving people
