### ISSUE TITLE
Fee information not matching fs.usda.gov site

### ISSUE THREAD

**Issue by dangelsaurus** [USDA/RIDB#64]
Looking at various sites on the fs.usda.gov site  (in this example we can reference https://www.fs.usda.gov/recarea/lincoln/recarea/?recid=34170) we see that Fee information is given in detail.

> $20 per night for single unit. 
> $9 per night for each additional vehicle 
> Showers (available at Silver CG):  $5 per person per use
> RV Dump Station (available at Silver CG):  $5 per use
> Water:  $0.25 per gallon after 1st free 5 gallons
> Trash:  $2.50 per bag per day
> Firewood (if available):  $6 per bag/bundle

However this information is not found in either the Facility Search `https://ridb.recreation.gov/api/v1/facilities/240794?apikey=myKey&full=true`
or the RecArea search
`https://ridb.recreation.gov/api/v1/recareas/1100?apikey=myKey&full=true`

**Comment by GitStu** [comment]
Some facilities/campgrounds on Recreation.gov are reservable in advance, and some are not.  Apache Campground is not reservable in advance.  Recreation.gov gets whatever data an agency (in this case the Forest Service) sends us, and for this one the fee data is not sent to us.  It is a common scenario for non-reservable facilities to not list their fee information on Rec.gov.  Note:  campsites at this (and others) campground can be reserved the day of arrival by just showing up, but none can be reserved in advance on the website.

[Forest Service Shield]

Stu Gregory
RIDB Data Manager

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/>[Forest Service Twitter]<https://twitter.com/forestservice>[USDA Facebook]<https://www.facebook.com/pages/US-Forest-Service/1431984283714112>

Caring for the land and serving people

**Comment by dangelsaurus** [comment]
Thanks for that information, that actually answers a few other questions I had as well.  I'm assuming no other resource exist for getting this data from the Forest Service via an API? (short of crawling the pages?)

**Comment by GitStu** [comment]
Please accept my apology.  I should have thought to take that next step and give you a Forest Service recreation data contact who might know how to get all the fee data.  Sue Valente, USFS Recreation Data Program Manager:  svalente@fs.fed.us<mailto:svalente@fs.fed.us>

[Forest Service Shield]

Stu Gregory
RIDB Data Manager

Forest Service
Recreation One Stop | Recreation.gov<http://www.recreation.gov/>

p: 801-975-3456
c: 801-602-2435
sgregory01@fs.fed.us<mailto:sgregory01@fs.fed.us>

2222 West 2300 South
Salt Lake City, UT 84119
www.fs.fed.us<http://www.fs.fed.us/>
[USDA Logo]<http://usda.gov/>[Forest Service Twitter]<https://twitter.com/forestservice>[USDA Facebook]<https://www.facebook.com/pages/US-Forest-Service/1431984283714112>

Caring for the land and serving people

**Comment by dangelsaurus** [comment]
Thank you very much for your time and help!
