### ISSUE TITLE
401 - Unauthorized: Access is denied due to invalid credentials.

### ISSUE THREAD

**Issue by shakil4014008** [USDA/RIDB#67]
https://ridb.recreation.gov/api/v1/facilities?state=CA
I have created account and uses basic authentication to send the request. Postman also give the same result.  when I run this command, it says unauthorized access. How to resolve the issue?

Thank you.
Shakil

**Comment by slouisin** [comment]
All API requests require an APIKey to authenticate.  If you have [not registered](https://ridb.recreation.gov/?action=register) with the RIDB, create an account or if you have, [sign in](https://ridb.recreation.gov/?action=login) and view your profile page to retrieve your unique apikey. 

http://usda.github.io/RIDB/#Authentication

Your request would be (replace xxxx with your unique key)
https://ridb.recreation.gov/api/v1/facilities?state=CA&apikey=xxxx

Thank you
RIDB Support

**Comment by shakil4014008** [comment]
Please let me know which authentication protocol it uses: Basic or Digest or oAuth1.o or any other. And followed the link you provided and some other ways to make it work. However, it did not. 

I tried to call from PHP and also from Postman, both says unauthorized. Here is my PHP code and output: 

Please suggest me.

code: 
<!DOCTYPE html>
<html>
<body>

<?php

function getchallenge($url)
{
   $accessToken = 'apikey:0DCA8435E0554257B58E04CAE9AD68F0';
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_USERPWD, $accessToken);
    curl_setopt($ch, CURLOPT_HTTPAUTH,  CURLAUTH_ANYSAFE);
    $output = curl_exec($ch);
    $info = curl_getinfo($ch);
    curl_close($ch);
    return $output;

}
$repos = getchallenge('https://ridb.recreation.gov/api/v1/recareas?query=yosemite');
echo  $repos;
print_r($repos);
?>
</body>
</html>

output: 
C:\xampp\php\php.exe C:\xampp\www\camp1\camptData.php
<!DOCTYPE html>
<html>
<body>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>
""<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>
""</body>
</html>

Process finished with exit code 0

**Comment by shakil4014008** [comment]
Thank you, it works now.
