### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by jmoe** [USDA/RIDB#8]
Would be nice if the service was configured with CORS to allow javascript clients to make requests from the browser without proxying. More info on CORS here:

http://en.wikipedia.org/wiki/Cross-origin_resource_sharing

Some examples of other APIs that have CORS support:

https://www.mapbox.com/developers/api/#cors
http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

**Comment by danparker-nsite** [comment]
Jereme,

Thanks for the recommendation for CORS support. We will evaluate this for consideration in an upcoming release.

**Comment by danparker-nsite** [comment]
Additional header information added to enable CORS.

`Access-Control-Allow-Origin: *`

Leaving ticket open for now to ensure no additional requirements are necessary.

**Comment by jmoe** [comment]
Looks like that header needs to be enabled for the OPTIONS request method as well. Sent email to Dan. Test code here:

https://gist.github.com/jmoe/09fd5828943b08f0b558

**Comment by danparker-nsite** [comment]
OPTIONS request header corrected on April 8th . This ticket is now complete. Thanks again for the collaboration on this, Jereme!
